### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by FabriceSalvaire** [mitchcurtis/slate#38]
**Compilation issues**

- explain we must install _undo_ in Qt
- _application.cpp_ remove `#include "url.h"`

**Test**

Totals: 54 passed, 44 failed, 0 skipped, 0 blacklisted

**Application**

Qt 5.11 on Fedora 27

* no menu
* zooming seems buggy
* painting is dotted if we move to fast

**Comment by mitchcurtis** [comment]
Thanks for the feedback. :)

> explain we must install undo in Qt

Did you build with Creator or from the command line? There are instructions for both [here](https://github.com/mitchcurtis/slate#building), and they should just work (i.e. without building submodules manually). What was the specific issue you ran into?

> application.cpp remove #include "url.h"

Ah, sorry about that. I think it's time that I started using branches instead of putting all my unstable stuff into master, since that's the branch you get by default when you clone.

> Totals: 54 passed, 44 failed, 0 skipped, 0 blacklisted

Can you please post the failure messages? The tests were passing for me last time I checked.

> Qt 5.11 on Fedora 27

I haven't tested it on Fedora, only Ubuntu. Which desktop environment/manager/whatever it's called does that use?

> no menu

This uses Qt Labs Platform. The [docs](http://doc.qt.io/qt-5/qml-qt-labs-platform-menubar.html#details) say:

> Linux (only available on desktop environments that provide a global D-Bus menu bar)

So it could be that I'll have to go back to using a non-native menu bar on some platforms. How I'm going to detect that at build time.. no idea.

> zooming seems buggy

I'm guessing you mean that it's too slow? I changed it a while back to improve it on the MacBook touchpad, but then it started being crappy with a mouse. I need to find a sweet spot.

I've created https://github.com/mitchcurtis/slate/issues/39 to track this.

> painting is dotted if we move to fast

This one has been around for a while. It's indeed not nice, but I also don't consider it a huge priority for Slate, as it's meant for doing up-close, pixel-by-pixel stuff, not sketches.

I've created https://github.com/mitchcurtis/slate/issues/39 to track this.

**Comment by FabriceSalvaire** [comment]
I tried to build from QtCreator and then using qmake. Both complain about missing unit.
I am on Kde.
All test passed with 5.11 beta 2.

**Comment by mitchcurtis** [comment]
> I think it's time that I started using branches instead of putting all my unstable stuff into master, since that's the branch you get by default when you clone.

I've been thinking about this a bit, and I don't really see the point in this. If I make `master` the stable branch and change the default branch (via GitHub's settings) to `dev` (to encourage all development to go there and so that I don't forget, as I have several different local copies of the repo), then that is the branch that users will get by default when they clone, which doesn't solve this issue. If I leave `master` as the (stable) default and add protection to it (all changes must be reviewed, since it would just take merges from `dev`), then it works, but I'm not sure if I like the idea of `master` being stable in the first place. I think that `master` should be open for people to submit changes to.

Since it's mostly just me working on this, and there are packaged releases and tags available, I'm going to document that these should be used instead.

With regards to the build issue, I can't do much without the actual failure messages, unfortunately. Feel free to open a separate issue for it. :)

**Comment by mitchcurtis** [comment]
https://bugreports.qt.io/browse/QTBUG-67426 tracks the missing menu bar in Qt.
